# Generated by Django 5.2.14 on 2026-08-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anthiasapitoken",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("fleet_management", "Fleet Management"),
                ],
                default="general",
                max_length=32,
            ),
        ),
    ]
