# Generated by Django 5.2.14 on 2026-08-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('anthias_app', '0007_asset_skip_ssl_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='authority',
            field=models.CharField(
                choices=[('local', 'Local'), ('fleet', 'Fleet')],
                default='local',
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name='asset',
            name='deployed_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='fleet_media_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='origin',
            field=models.CharField(
                choices=[('local', 'Local'), ('fleet', 'Fleet')],
                default='local',
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name='asset',
            name='source_deployment_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
