"""The unauthenticated half of the pairing protocol (plan §8) — the
two endpoints a Player calls before it has (``poll``) or right after
receiving (``ack``) a device credential. The authenticated,
admin-facing half (list/approve/revoke) lives on ``PlayerViewSet`` and
``PairingRequestViewSet`` in ``api.views`` instead, since those are
ordinary RBAC-scoped org resources.

There is deliberately no separate "register" endpoint: per the plan's
step 2/3, the pairing code pair is generated by the Player, not
issued by Fleet, so the *first* poll that presents a given device code
is what creates the ``PairingRequest`` row — see
``PairingPollView.post``.
"""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import Any

from django.core.cache import cache
from django.utils import timezone
from rest_framework import status
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.throttling import ScopedRateThrottle
from rest_framework.views import APIView

from anthias_fleet_server.api.authentication import (
    AuthenticatedPlayer,
    PlayerCredentialAuthentication,
    hash_player_credential,
    issue_player_credential,
)
from anthias_fleet_server.api.serializers import PairingPollRequestSerializer
from anthias_fleet_server.core.models import PairingRequest, PlayerCredential

# How long a pairing code stays valid fleet-side, enforced
# independently of whatever TTL the Player displays locally — see the
# plan's §17 note that a client-supplied expiry can't be trusted for a
# security-relevant window.
_PAIRING_REQUEST_TTL = timedelta(minutes=10)

# Floor on how often the *same* device code may poll, on top of the
# IP-bucketed ScopedRateThrottle below — §17.1/§17.5 flag the pairing
# endpoints as needing both. A single misbehaving/compromised Player
# hammering its own code shouldn't be able to outrun this even from a
# rotating set of source IPs.
_DEVICE_CODE_POLL_MIN_INTERVAL_S = 4


def _device_code_poll_allowed(device_code_hash: str) -> bool:
    """Atomic per-device-code rate gate via ``cache.add`` (returns
    False if the key is already set) — same lightweight, in-process-
    cache-is-fine posture as the Player's own basic-auth deprecation
    log throttle (``anthias_server.lib.auth._should_log_basic_auth_use``).
    """
    key = f'pairing:poll:{device_code_hash}'
    return cache.add(key, 1, timeout=_DEVICE_CODE_POLL_MIN_INTERVAL_S)


class PairingPollView(APIView):
    """A Player's outbound pairing poll. Unauthenticated by necessity
    — pairing is how trust gets established in the first place — so
    every response here is safe to reveal to an unauthenticated
    caller who merely knows a device code, which is why it never
    echoes back anything about *other* pairing requests (the
    user-code collision check below responds identically whether the
    colliding code belongs to a real pending request or not).
    """

    permission_classes = (AllowAny,)
    authentication_classes = ()
    throttle_classes = (ScopedRateThrottle,)
    throttle_scope = 'pairing'

    def post(self, request: Request) -> Response:
        serializer = PairingPollRequestSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        device_code = serializer.validated_data['device_code']
        user_code = serializer.validated_data['user_code']
        device_id = serializer.validated_data.get('device_id')
        label = serializer.validated_data.get('device_label', '')

        device_code_hash = hash_player_credential(device_code)
        if not _device_code_poll_allowed(device_code_hash):
            return Response(
                {'error': 'Too many requests for this device code.'},
                status=status.HTTP_429_TOO_MANY_REQUESTS,
            )

        now = timezone.now()
        pairing_request = PairingRequest.objects.filter(
            device_code_hash=device_code_hash
        ).first()

        if (
            pairing_request is not None
            and pairing_request.status == PairingRequest.PENDING
            and pairing_request.expires_at <= now
        ):
            pairing_request.delete()
            return Response({'status': 'expired'})

        if pairing_request is None:
            # A colliding *live* user_code from a different device is
            # rejected outright rather than silently attached to
            # this request — see the module docstring and §17.5:
            # single-use codes are only meaningful if a collision is
            # a hard error, not a shared registration.
            collision = (
                PairingRequest.objects.filter(
                    user_code=user_code, status=PairingRequest.PENDING
                )
                .exclude(device_code_hash=device_code_hash)
                .exists()
            )
            if collision:
                return Response(
                    {'status': 'code_collision'},
                    status=status.HTTP_409_CONFLICT,
                )
            PairingRequest.objects.create(
                user_code=user_code,
                device_code_hash=device_code_hash,
                device_id=device_id,
                label=label,
                expires_at=now + _PAIRING_REQUEST_TTL,
            )
            return Response({'status': 'pending'})

        if pairing_request.status == PairingRequest.PENDING:
            return Response({'status': 'pending'})

        if pairing_request.status == PairingRequest.APPROVED:
            return Response(self._deliver_credential(pairing_request, now))

        return Response({'status': 'completed'})

    @staticmethod
    def _deliver_credential(
        pairing_request: PairingRequest, now: datetime
    ) -> dict[str, Any]:
        """Issue a fresh credential for an approved request, revoking
        whatever was handed out on a previous poll that the Player
        never acknowledged. Reissuing (rather than "hand it out
        once") is what makes a dropped response recoverable — see the
        plan's interrupted-pairing requirement and
        ``PairingRequest``'s class docstring.
        """
        assert pairing_request.player is not None
        if pairing_request.pending_credential_id is not None:
            PlayerCredential.objects.filter(
                pk=pairing_request.pending_credential_id
            ).update(revoked_at=now)
        credential_row, raw_credential = issue_player_credential(
            pairing_request.player
        )
        pairing_request.pending_credential = credential_row
        pairing_request.save(update_fields=['pending_credential'])
        return {
            'status': 'approved',
            'credential': raw_credential,
            'player_id': str(pairing_request.player_id),
        }


class PairingAckView(APIView):
    """A Player's acknowledgement that it received and stored a
    credential — the first real use of ``PlayerCredentialAuthentication``,
    which the (later) sync engine will reuse for every subsequent
    call. Completing the request here is what stops
    ``PairingPollView`` from reissuing further credentials for it.
    """

    authentication_classes = (PlayerCredentialAuthentication,)
    permission_classes = (IsAuthenticated,)
    throttle_classes = (ScopedRateThrottle,)
    throttle_scope = 'pairing'

    def post(self, request: Request) -> Response:
        principal = request.user
        assert isinstance(principal, AuthenticatedPlayer)
        pairing_request = (
            PairingRequest.objects.filter(
                player=principal.player, status=PairingRequest.APPROVED
            )
            .order_by('-approved_at')
            .first()
        )
        if pairing_request is None:
            return Response(
                {'error': 'No approved pairing request to acknowledge.'},
                status=status.HTTP_404_NOT_FOUND,
            )
        pairing_request.status = PairingRequest.COMPLETED
        pairing_request.completed_at = timezone.now()
        pairing_request.save(update_fields=['status', 'completed_at'])
        return Response({'status': 'completed'})
