# Generated by Django 5.2.14 on 2026-08-13 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PlayerGroup',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fleet_player_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField()),
                ('base_url', models.URLField()),
                ('api_token_encrypted', models.TextField()),
                ('skip_ssl_verify', models.BooleanField(default=False)),
                ('mac_address', models.TextField(blank=True)),
                ('device_model', models.TextField(blank=True)),
                ('anthias_version', models.TextField(blank=True)),
                ('is_reachable', models.BooleanField(default=False)),
                (
                    'last_reachability_check',
                    models.DateTimeField(blank=True, null=True),
                ),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'group',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='players',
                        to='fleet.playergroup',
                    ),
                ),
            ],
            options={
                'db_table': 'fleet_players',
                'ordering': ['name'],
            },
        ),
    ]
