# Generated by Django 5.2.14 on 2026-08-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='display_power',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='free_space',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='loadavg_15min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='memory',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='player',
            name='up_to_date',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='uptime_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='uptime_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
