# Generated by Django 5.2.14 on 2026-08-14 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fleet', '0002_player_telemetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPushJob',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('source_asset_id', models.TextField()),
                ('asset_name', models.TextField(blank=True)),
                ('mimetype', models.CharField(blank=True, max_length=16)),
                ('duration', models.PositiveIntegerField(default=10)),
                ('source_uri', models.TextField(blank=True)),
                ('staged_content_path', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='push_jobs',
                        to='fleet.playergroup',
                    ),
                ),
                (
                    'source_player',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='fleet.player',
                    ),
                ),
            ],
            options={
                'db_table': 'fleet_asset_push_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetPushJobTarget',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('success', 'Success'),
                            ('failed', 'Failed'),
                            ('skipped', 'Skipped'),
                        ],
                        default='pending',
                        max_length=16,
                    ),
                ),
                ('error', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'job',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='targets',
                        to='fleet.assetpushjob',
                    ),
                ),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='fleet.player',
                    ),
                ),
            ],
            options={
                'db_table': 'fleet_asset_push_job_targets',
                'ordering': ['player__name'],
            },
        ),
    ]
