# Generated by Django 5.2.14 on 2026-08-14 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fleet', '0003_assetpushjob_assetpushjobtarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistTemplate',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='playlist_templates',
                        to='fleet.playergroup',
                    ),
                ),
            ],
            options={
                'db_table': 'fleet_playlist_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTemplateItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField()),
                ('uri', models.URLField()),
                (
                    'mimetype',
                    models.CharField(
                        choices=[
                            ('image', 'Image'),
                            ('video', 'Video'),
                            ('webpage', 'Webpage'),
                        ],
                        max_length=16,
                    ),
                ),
                ('duration', models.PositiveIntegerField(default=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('play_days', models.TextField(blank=True)),
                ('play_time_from', models.TimeField(blank=True, null=True)),
                ('play_time_to', models.TimeField(blank=True, null=True)),
                (
                    'template',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='fleet.playlisttemplate',
                    ),
                ),
            ],
            options={
                'db_table': 'fleet_playlist_template_items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateApplicationJob',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'template',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='application_jobs',
                        to='fleet.playlisttemplate',
                    ),
                ),
            ],
            options={
                'db_table': 'fleet_template_application_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateApplicationJobTarget',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('success', 'Success'),
                            ('failed', 'Failed'),
                        ],
                        default='pending',
                        max_length=16,
                    ),
                ),
                ('error', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'job',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='targets',
                        to='fleet.templateapplicationjob',
                    ),
                ),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='fleet.player',
                    ),
                ),
            ],
            options={
                'db_table': 'fleet_template_application_job_targets',
                'ordering': ['player__name'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTemplatePlacement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('remote_asset_id', models.TextField()),
                ('last_applied_at', models.DateTimeField(auto_now=True)),
                (
                    'item',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='placements',
                        to='fleet.playlisttemplateitem',
                    ),
                ),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='fleet.player',
                    ),
                ),
                (
                    'template',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='placements',
                        to='fleet.playlisttemplate',
                    ),
                ),
            ],
            options={
                'db_table': 'fleet_playlist_template_placements',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('item', 'player'),
                        name='unique_placement_per_item_player',
                    )
                ],
            },
        ),
    ]
