# Generated by Django 5.2.14 on 2026-08-16 00:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('command_id', models.TextField(unique=True)),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('reboot', 'Reboot'),
                            ('shutdown', 'Shutdown'),
                            ('restart_player', 'Restart player'),
                            ('refresh_content', 'Refresh content'),
                            ('take_screenshot', 'Take screenshot'),
                            ('update_software', 'Update software'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('running', 'Running'),
                            ('succeeded', 'Succeeded'),
                            ('failed', 'Failed'),
                        ],
                        default='pending',
                        max_length=16,
                    ),
                ),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fleet_link_command',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FleetPairing',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('fleet_base_url', models.URLField()),
                ('fleet_org_id', models.TextField(blank=True, null=True)),
                ('device_credential', models.TextField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('active', 'Active'),
                            ('revoked', 'Revoked'),
                        ],
                        default='pending',
                        max_length=8,
                    ),
                ),
                (
                    'content_authority',
                    models.CharField(
                        choices=[('local', 'Local'), ('fleet', 'Fleet')],
                        default='local',
                        max_length=8,
                    ),
                ),
                (
                    'playlist_authority',
                    models.CharField(
                        choices=[('local', 'Local'), ('fleet', 'Fleet')],
                        default='local',
                        max_length=8,
                    ),
                ),
                (
                    'schedule_authority',
                    models.CharField(
                        choices=[('local', 'Local'), ('fleet', 'Fleet')],
                        default='local',
                        max_length=8,
                    ),
                ),
                (
                    'config_authority',
                    models.CharField(
                        choices=[('local', 'Local'), ('fleet', 'Fleet')],
                        default='local',
                        max_length=8,
                    ),
                ),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('unpaired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fleet_link_pairing',
            },
        ),
        migrations.CreateModel(
            name='PlayerIdentity',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'device_id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fleet_link_player_identity',
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'domain',
                    models.CharField(
                        choices=[
                            ('media', 'Media'),
                            ('content', 'Content'),
                            ('config', 'Config'),
                        ],
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    'desired_version',
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    'applied_version',
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    'last_attempt_at',
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    'last_success_at',
                    models.DateTimeField(blank=True, null=True),
                ),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fleet_link_sync_state',
            },
        ),
    ]
