# Generated by Django 5.2.14 on 2026-08-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet_link", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleetpairing",
            name="pairing_code_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fleetpairing",
            name="pairing_device_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fleetpairing",
            name="pairing_user_code",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
